### ISSUE TITLE
Question about Specific Platform Repo...

### ISSUE THREAD

**Issue by giorgionetg** [ToastWallet/core#10]
> This contains the core javascript and css of the wallet. Each specific platform has a repo that wraps the html5 app.

Where are the specific repo? Are these public? And why not? I couldn't find... Where could I find?

Thanks a lot..

Giorgio

**Comment by xulture** [comment]
This repo contains everything I needed to test changes and build 'development' version of the app for android.  I haven't tried other platforms.  From what I gather, only parts required to sign the app for releases to the stores are not included, and they shouldn't be public or else anyone can release software on behalf on official developer....

**Comment by giorgionetg** [comment]
You are speaking about Android repo. I mean where is other kind of repo? For Windows repo there is no need to be official developer (at least you are doing a repo to share with windows store).
And anyway, you put Official Developer credentials some where not shared with github.
I mean, it's not so much "open source" this project.
I can't verify for example the process of architecture you or official developer shown on website. Does it right? Or it's a my misunderstanding?

**Comment by xulture** [comment]
No, I'm speaking about this repo -- I only used this 'core' repo.

**Comment by giorgionetg** [comment]
Ok, I apologize.. I thought the scripts are external as libraies used... Not inside main html. So sorry.. ;-)

**Comment by xulture** [comment]
No problem, i thought that too initially, but then went ahead to give it a go -- and yeah everything to get operational wallet is there :-)
