### ISSUE TITLE
Restore an existing Wallet on mobile

### ISSUE THREAD

**Issue by jimmysoho** [ToastWallet/core#16]
I have a ToastWallet on my Desktop. Can I work with that wallet with my mobile as well? I thought I could "Restore an Existing Wallet" on my mobile, but do I then have to type in manually that enormously long string that looks like JSON from the Wallet Backup of my Desktop version? That's hardly doable. Is there an easier way?

**Comment by SneakyFish5** [comment]
Just copy paste it into there?

**Comment by jimmysoho** [comment]
I wouldn't know how to securely get that string on my mobile, but I'll figure it out.

I don't understand the Wallet Backup though. If use https://github.com/jatchili/minimalist-ripple-client and enter only the 30 character long secret of my wallet then I have full control over the wallet. What does a "Wallet Backup" of Toast actually do?? Why is it not possible to enter that secret on my mobile in the Toast Wallet to have control over my wallet on my mobile?

**Comment by SneakyFish5** [comment]
You can import a secret key as well, the backup is just there as an “enecrypted” version of your wallet. So when you recover it via backup code, you use that plus your passphrase/recovery phrase to unlock the secrets and restore your wallet. 

Importing your secret key directly isn’t encrypted and generally less safe unless you are typing it in manually, then you should be ok.

**Comment by jimmysoho** [comment]
The text presented when creating a ToastWallet is:

```
IMPORTANT!!!
Your six(6) word recovery phrase appears below. Write it down on paper and store in a safe location. If you ever forget your passphrase this code will be the only way for you to regain access to your XRP.
```

But that seems not to be true. With a forgotten passphrase I can still access my XRP, provided I have the secret key. Therefor, imo it's best to write down the secret  key on paper and store in a safe location.

I don't see the added advantage of a passphrase above the secret key. Both are secret, and both unlock access to your XRPs.

**Comment by smart-t** [comment]
Just a related issue, I think... So I just created a Toast wallet on my Mac (OS High Sierra) I copied the backup JSON string to my mobile where I attempt to rebuild a copy of my wallet. Using the exact same string to restore, I still get that I did not have the same string (no recovery possible). This is strange, I double . ... tripple checked for misplaced spaces. But nothing like that. Ps. I am using an Android 8.0 phone. Hope you can help.

**Comment by SneakyFish5** [comment]
You can check the backup phrase here: https://toastwallet.com/backupcheck/

**Comment by smart-t** [comment]
Yes, I just got that clue from Nate on discord. That worked for me, so all issues resolved for me. Thanks for coming back @SneakyFish5 !
