### ISSUE TITLE
Forced Fullscreen Mode

### ISSUE THREAD

**Issue by anwarkaram** [ToastWallet/core#18]
Hey guys, great app! Can you guys reconsider fullscreen mode on the Android app? It is really clunky right now because the navigational buttons are hidden until you swipe up from the bottom of the screen. Swiping up from the bottom of the screen causes one of the tab actions to be executed due to the 'on down event' rather than the Android standard 'on up event'. 

This is likely due to stock Cordova logic causing any touch event to trigger an 'on click' event. Anyway, it seems the app would work fine in a non-fullscreen mode fashion.

**Comment by codetsunami** [comment]
This was finally fixed a couple of versions ago
