### ISSUE TITLE
Sent XRP from ToastWallet to binance. XRP didn't make it, no transaction log. It's as if it just vanished.

### ISSUE THREAD

**Issue by petermalone** [ToastWallet/core#19]
As the topic says, XRP blockchain was under pressure today. I sent XRP from my wallet to binance and it never made it. Binance asked me to reach out to you. I suspect it's their issue but trying to find a transaction id from you - nothing shows up in my wallet. 

Lots of folks reporting the same issue.

**Comment by jimmysoho** [comment]
Go to https://bithomp.com/explorer/ and enter your wallet address. Under "Transactions" you should see the transaction to binance. Click on the "i" symbol to see the details, including the transaction ID.

**Comment by ToastWallet** [comment]
We will be implementing our own history solution in the future.

**Comment by claybyrd1551** [comment]
Is toaster wallet closing?
