### ISSUE TITLE
Feature Request:  Add 2FA 

### ISSUE THREAD

**Issue by jovincroninwilesmith** [ToastWallet/core#20]
I believe it would be useful to implement 2FA for the Toast Wallet. It is not only incredibly user-friendly now with services like Google Authenticator and such, but adds a layer of security that cannot be captured with a simple passcode.

**Comment by jovincroninwilesmith** [comment]
Maybe this could be trigger when taking impactful actions like sending XRP?

**Comment by ToastWallet** [comment]
The only way to add a second factor of authentication to a Ripple account is using multi-sign. While support for this is planned for Toast Wallet eventually it is a long way down the road map. There are numerous more important additions to make first.

**Comment by jovincroninwilesmith** [comment]
Ok cool! Thanks for letting me know. Love where the project is going.
