### ISSUE TITLE
recovery phrase

### ISSUE THREAD

**Issue by sergiosouto10** [ToastWallet/core#22]
Hi there, somehow i lost my recovery phrase and my pass phrase, i only know my pin number, is there anything i can do to get back my recovery phrase? so ill be able to fix my problem.
since now thank you very much for your help.

**Comment by anorouzi2000** [comment]
Hi man 
I have the same problem
I had lost my phone just one day after making my account
It was so important for me i know the pin and can remember just some oart of my pass pharaze 
Help me plz

**Comment by SneakyFish5** [comment]
Do either of you have your Ripple Secret?

**Comment by ToastWallet** [comment]
You need either recovery phrase or passphrase to unlock your wallet.

**Comment by sergiosouto10** [comment]
So in case that I don’t remember my pass or recovery phrase, there is nothing I can do but loose all I have in this account???

**Comment by sergiosouto10** [comment]
Hey Sneakyfish5 thanks for trying to help, 
No I only have my PIN number. Do u know if is there a chance still?
