### ISSUE TITLE
Potential Error: Sending XRP 

### ISSUE THREAD

**Issue by jovincroninwilesmith** [ToastWallet/core#23]
I have tried to send XRP to multiple accounts and keep getting hit with the error _"An error occurred when trying to make your payment. Most likely lack of funds in the account you are sending from. ( The network requires a minimum account balance.) This error can also be caused by an invalid or not activated destination address or if the Ripple network is overloaded."_ 

I have tried multiple addresses including the address for sending tips and nothing seems to progress. 

Additionally, I have ample XRP in the address I am sending from. 
<img width="329" alt="screen shot 2018-01-10 at 3 38 59 pm" src="https://user-images.githubusercontent.com/4871208/34778042-697ad446-f61c-11e7-8b6d-b7bdb244af56.png">

Please let me know if you have any idea why this may be happening.

**Comment by jovincroninwilesmith** [comment]
Lastly, I have used the account explorer to validate there are funds.
<img width="193" alt="screen shot 2018-01-10 at 3 44 28 pm" src="https://user-images.githubusercontent.com/4871208/34778306-4799a4fa-f61d-11e7-9780-f01441de8f59.png">

**Comment by denizdogan** [comment]
I have the exact same error. Very frustrating, but relieved to see I'm not the only one.

**Comment by SneakyFish5** [comment]
This is most likely because of Ripple Gateway congestion, an update is coming soon to help fix this.

**Comment by jovincroninwilesmith** [comment]
@denizdogan what was the timeframe in which you waited before it worked? I am still experiencing the same issue.

**Comment by ToastWallet** [comment]
The gateway cycling update has been pushed to the repo. It's being rolled out now. This should largely fix this issue.

**Comment by jovincroninwilesmith** [comment]
Confirmed fix :) Thanks so much
