### ISSUE TITLE
Stay on the transaction screen if there is a problem sending XRP

### ISSUE THREAD

**Issue by denizdogan** [ToastWallet/core#24]
Related to #23, I really need to transfer XRP to another address, but there is some error and I'm returned to the previous screen. It would be nice if I stayed on the send screen if there is an error, so I don't have to scan the QR code again or enter the (complicated) passphrase again. (I can't stand typing on a phone with my Shrek thumbs...)

Thanks for this project!

**Comment by ToastWallet** [comment]
The latest update causes the app to cycle through all available gateways before reporting a transaction send failure. We have planned another transaction sending update which will include the feature you request.

**Comment by codetsunami** [comment]
This is fixed in the upcoming release.
