### ISSUE TITLE
Local folder path for DB saving, Useful for portable apps

### ISSUE THREAD

**Issue by mkimid** [ToastWallet/core#25]
It is just a suggestion, not an issue. 
Is there any method (or improvement) to save a DB into User specific folder. 
Actually, APP is saved into a computer in %appdata%/toastwallet for windows system. 
If this folder can be specified into a USB drive (or any location), Is it will be useful as a hardware wallet ?

**Comment by ToastWallet** [comment]
There's most likely a way to configure it in electron builds. We're flat out with other improvements at the moment but if you work it out reply here or open a pull request and we'll jump on it. Thanks!

**Comment by codetsunami** [comment]
The portable version of Toast for Windows saves to the path the executable runs from
