### ISSUE TITLE
Trailing zeros destination tag fails

### ISSUE THREAD

**Issue by jmdiego** [ToastWallet/core#29]
If I try to use a valid destination tags that includes trailing zeros, it fails:

![image](https://user-images.githubusercontent.com/4139160/35080076-069791e2-fbd1-11e7-86db-70739186af3b.png)

**Comment by ToastWallet** [comment]
Good find. Destination tag is transmitted as an integer so the zeros on the front will do nothing. Try sending without them. We'll fix this in an upcoming update.

**Comment by codetsunami** [comment]
This was fixed sometime ago thanks
