### ISSUE TITLE
connectivity

### ISSUE THREAD

**Issue by silverbuyer** [ToastWallet/core#30]
if i setup my own ripple network..how do i point the wallet to my own domain?

**Comment by ToastWallet** [comment]
If you run a validator that is synced to the rest of the Ripple network you can just add your validator as a gateway from the settings menu.

If you want to fork the Ripple network and point your copy of Toast at it you'll need to modify the serverStack variable.

**Comment by silverbuyer** [comment]
how do you do that? looking at sawtooth demo to work with different assets
in each user account..click on account after signup to see user assets
need to transfer to other users any asset in user account. check
balance..transaction history..let me know if it could be done easily.

thanks!
https://demo.bitwise.io/sawbucks/#!/assets

**Comment by silverbuyer** [comment]
in your first scenario what would that do for me? i want i run my own assets..i dont believe you can run your own assets on the ripple network like etherium.


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Toast Wallet <notifications@github.com> Date: 2018-02-02  10:07 PM  (GMT-05:00) To: ToastWallet/core <core@noreply.github.com> Cc: silverbuyer <showbox654265@gmail.com>, Author <author@noreply.github.com> Subject: Re: [ToastWallet/core] connectivity (#30) 
If you run a validator that is synced to the rest of the Ripple network you can just add your validator as a gateway from the settings menu.
If you want to fork the Ripple network and point your copy of Toast at it you'll need to modify the serverStack variable.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ToastWallet/core","title":"ToastWallet/core","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ToastWallet/core"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ToastWallet in #30: If you run a validator that is synced to the rest of the Ripple network you can just add your validator as a gateway from the settings menu.\r\n\r\nIf you want to fork the Ripple network and point your copy of Toast at it you'll need to modify the serverStack variable."}],"action":{"name":"View Issue","url":"https://github.com/ToastWallet/core/issues/30#issuecomment-362772534"}}}
