### ISSUE TITLE
Ripple URIs in QR codes

### ISSUE THREAD

**Issue by ToastWallet** [ToastWallet/core#4]
Some exchanges (shapeshift for example) provide their users with a QR code which contains a Ripple URI. However no officially supported URI scheme currently exists.

To our knowledge these URIs are generally formatted like so: ripple:<address>&dt=<destination tag> 
However other exchanges might use other formats.

A roundup of common defacto formats should be made and an intelligent parser built out of multiple regular expressions to be attached to the QR code scanner for ease of user interaction.

This is the only published documentation on Ripple URIs and it is quite clearly abandoned:
https://wiki.ripple.com/Ripple_URIs

We have PM'd David Schwartz on xrpchat.com about this issue but have not received a response -- possibly indicating that Ripple Labs do not have a policy on these URIs at all currently.

**Comment by codetsunami** [comment]
https://github.com/xrp-community/standards-drafts/issues/3
