### ISSUE TITLE
Uncaught TypeError on launch

### ISSUE THREAD

**Issue by NetScr1be** [ToastWallet/core#41]
Source: Toast Discord #help

Problem Statement: Multiple users reporting the following error when opening the app (and when updating passphrase);

> We're sorry: An unexpected error has occured with Toast Wallet. Please report the below to support@toastwallet.com along with what you were trying to do at the time the error occured. If you haven't already it would be prudent to make a backup of your wallet. You may need to restart Toast Wallet by closing it manually. Uncaught TypeError: Keyboard.shrinkView is not a function https://toastwallet.com/browser/index.html 113

Appears to be version dependent as it has not been seen in existing app instances running on older versions of browsers (tested in both Chrome 68 and Opera <latest>).

Web search turns up [Medium article citing (undocumented?) keyboard API as the source of the issue](https://medium.com/@k1d_bl4ck/the-mysterious-keyboard-api-of-chrome-v68-a151d787e1d).

Does **_not_** occur in:

`
Version: | 54.0.2952.71 - Restart Opera to update to version 55.0.2994.37 
Stable
Windows 7 32-bit
`

**Comment by crabbit49** [comment]
i can confirm it happens immediately when toast opens with no action on my part

**Comment by codetsunami** [comment]
This was fixed a while ago as far as I know. If not open a new issue.
