### ISSUE TITLE
recovery phrase rejected

### ISSUE THREAD

**Issue by crabbit49** [ToastWallet/core#42]
I have restored my wallet using my backup and recovery phrase, now every time I try to use my recovery phrase it is rejected as the wrong set of words, I have forgotten my passphrase and want to change it

**Comment by crabbit49** [comment]
There are numerous people who are having the same problem

**Comment by crabbit49** [comment]
Does anybody ever take any notice of the ordinary man in the street's problems ?

**Comment by crabbit49** [comment]
Apparently not

**Comment by codetsunami** [comment]
You are the only person I know of that has this problem and I believe it has to do with a possible bug in a system library of the specific phone you used to create your account. As I have advised you previously: please obtain another phone of this model and attempt to restore on that.

**Comment by crabbit49** [comment]
Why do you close every post I make complaining about toast wallet misfunction ? I have tried another s7 and I still get the same result, it rejects my memorable words, as I have said before, I am not the only person with this problem

**Comment by crabbit49** [comment]
"quote by Richard"  You are the only person I know of that has this problem "unquote"
That is a complete and utter lie, I think you need to refresh your memory by reading past posts on your Discord group page

**Comment by codetsunami** [comment]
The code is open source it’s right there. If you can find the bug please fix it and submit a pull request. At this stage I don’t believe there is a bug, I believe you simply did not record your recovery phrase correctly. Until you can identify code that is causing the alleged problem you are spamming. Please stop.

**Comment by crabbit49** [comment]
You are the app developer, not me, if i knew how to read code I would look for the bug, but as I don't know how to, I tend to trust people like yourself to investigate and rectify the problem,... Before you tell me to ask a friend who is code literate, I don't know anyone ....  Please explain to me how I managed to reinstall my wallet on a new device by using the backup and memorable phrase, but when I try to change said phrase it is rejected

**Comment by codetsunami** [comment]
You don’t need your recovery phrase to restore a backup. I’ve explained this to you before. The backup contains your encrypted keys. The keys are not decrypted during restore, only when you send.
