### ISSUE TITLE
Account not activated after restore 

### ISSUE THREAD

**Issue by guyoosh1** [ToastWallet/core#45]
Hi everyone,
I have restored my exciting wallet which I opened from my PC to my mobile app and it’s says that it is not been activated.
I have a nice amount of Ripples there.

I have also downloaded the wallet to my new PC after recovery and same thing there. 
What should I do?

**Comment by NetScr1be** [comment]
Apologies for the delayed response. This forum is not monitored for support issues.

Go to Discord to report support issues please: https://discord.gg/SZAyh2T

The issue reported can occur if the backup restored was taken prior to activation.

Backups are a snapshot of current account state and will revert state back to time of snapshot when restored.

Update backups when account state changes (e.g. activated, password change)

**Comment by crabbit49** [comment]
Toast wallet is a ripoff,  there are numerous people who have saved their memorable phrase correctly, but when it  comes to using it, it is rejected as the wrong set of words
