### ISSUE TITLE
Deeplinks die at pin entry screen

### ISSUE THREAD

**Issue by copleykj** [ToastWallet/core#49]
I'm currently using a deeplink (`xrpl://`) to provide a quick way for users to send payment if they are already on their mobile device and therefore can't scan the provided QR. Toast wallet handles the intent properly and opens the app; however if the app isn't already open and unlocked the pin entry screen is shown. If I then enter the pin it opens the app, but not to a payment screen with the proper info entered, but to the default accounts screen.

**Comment by codetsunami** [comment]
This bug has been fixed in the upcoming release. If you experience any other issues with deeplinks please open a new issue, thanks!

**Comment by copleykj** [comment]
Thanks buddy
