### ISSUE TITLE
Feature request - Allow restore of Ripple wallet using HEX private key from wallet apps using BIP44.

### ISSUE THREAD

**Issue by jonathanq9** [ToastWallet/core#51]
Can you add support for restoring Ripple wallet using HEX private key from wallet apps using BIP44?

From Exodus.io app Ripple account is exported as private key, for example "f3ff9817dacfe1ae2522894f33696a7e26ffb1e2892b6bfe72434a0000000000" (not actual private key)

The ToastWallet is expecting the Ripple secret key, for example "snoPBrXtMeMyMHUVTgb0000000000"

I used the offline version of this website with my 12-word recovery seed for testing.
https://iancoleman.io/bip39/

BIP32 Derivation Path for XLM = m/44'/144'/0'/0

**Comment by codetsunami** [comment]
Did you want to try fork https://github.com/WietseWind/toastify-ledger/releases and modify it for this specific usecase?

**Comment by jonathanq9** [comment]
No longer need this, closing.
