### ISSUE TITLE
Feature Request/ Inquiry - Android Intent to load with receivers address

### ISSUE THREAD

**Issue by CodeWardNinja** [ToastWallet/core#55]
Hi there, 

I'm starting to hash out a project, and was wondering if there's a way to use an intent in one app to open ToastWallet straight to the send screen (after PW screen, of course) with receivers address (and possibly the amount) pre-populated from the intent?

Not sure if this is something that's implemented already. 

Regards,
Codeward

**Comment by codetsunami** [comment]
Hi Codeward

Yes you can use an xrpl:// deep link to do this. For example a valid format is: xrpl://<address>?amount=xxx&dt=yyy

Navigate here to see a working example https://toastwallet.com/test

See https://github.com/xrp-community/standards-drafts/issues/3 for URI details

**Comment by CodeWardNinja** [comment]
Hi codetsunami,

Thank you very much for your quick reply. 👍 

That's awesome and will suit my needs perfectly.

**Comment by bogdyak** [comment]
Hello

> Navigate here to see a working example https://toastwallet.com/test

Should that URI work on mac, win, linux ?
