### ISSUE TITLE
Error msg when sending XRP from Toast to Kraken.

### ISSUE THREAD

**Issue by Ffrankkk** [ToastWallet/core#65]
Hi All,

I have a toast wallet and would like to transfer lets say 100 xrp to my kraken account.
I get below printscreen error msg, was hoping if there is somebody that can help me with this?
it refers to overloaded toast wallet connects.

I leave at least 20 xrp in the account.

![printscrn toast](https://user-images.githubusercontent.com/82102653/113879246-9be32d00-97ba-11eb-9ace-f141535d6fd5.PNG)

Hope you can help!!

Kind regards,

**Comment by Ffrankkk** [comment]
Hi Guys,

I made a back up of wallet, reinstalled in on my Desktop, all works now.

Cheers!

**Comment by mec1007** [comment]
Hey Frank, how are you, I am having the same problem. I did a restore but still with an issue. Can you help me?

**Comment by Ffrankkk** [comment]
Happy to help, but I am not a pro. 

I went to the site of toastwallet and used my login details there, which did the trick. 

Hope it works for you, I probably had an old software version of my mobile/toastwallet. 

Good luck, 

Frank
